services:
  #Base de Datos Principal
  postgres-db:
    image: postgres:15-alpine
    container_name: fintech-postgres
    ports:
      - "5433:5432" # Puerto PC : Puerto Contenedor
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=core_banking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia (para no perder datos al apagar)
    networks:
      - fintech-network

  # Interfaz Gráfica para ver la DB
  pgadmin:
    image: dpage/pgadmin4
    container_name: fintech-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - fintech-network

  # Microservicios java

  api-gateway:
    build: ./api-gateway 
    container_name: api-gateway
    ports:
      - "8080:8080" # Expuesto al mundo
    environment:
      # URLs internas de Docker
      - CORE_URL=http://core-banking:8090
      - AUDIT_URL=http://audit-service:8082
    depends_on:
      - core-banking
      - audit-service
    networks:
      - fintech-network

  notification-service:
    build: ./notification-service/notification-service
    container_name: notification-service
    ports:
      - "8081:8081"
    networks:
      - fintech-network

  audit-service:
    build: ./audit-service/audit-service
    container_name: audit-service
    ports:
      - "8082:8082"
    environment:
      # OJO: Dentro de la red Docker usamos el puerto interno 5432 y el host 'postgres-db'
      - DB_URL=jdbc:postgresql://postgres-db:5432/audit_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - postgres-db
    networks:
      - fintech-network

  core-banking:
    build: ./core-banking/core-banking
    container_name: core-banking
    ports:
      - "8090:8090"
    environment:
      - SERVER_PORT=8090
      - DB_URL=jdbc:postgresql://postgres-db:5432/core_banking_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      # Aquí le decimos dónde están sus hermanos
      - NOTIFICATION_URL=http://notification-service:8081
      - AUDIT_URL=http://audit-service:8082
    depends_on:
      - postgres-db
      - notification-service
      - audit-service
    networks:
      - fintech-network

volumes:
  postgres_data:

networks:
  fintech-network:
    driver: bridge